[workspace]
resolver = "2"
members = ["crates/*"]

[workspace.package]
version = "0.0.1"
edition = "2021"
license = "MIT"

[workspace.dependencies]
mtr-core = { path = "crates/mtr-core" }
mtr-instrument = { path = "crates/mtr-instrument" }
mtr-types = { path = "crates/mtr-types" }
mtr-mutators = { path = "crates/mtr-mutators" }
mtr-runner-jest = { path = "crates/mtr-runner-jest" }
mtr-runner-vitest = { path = "crates/mtr-runner-vitest" }
mtr-test-runner-api = { path = "crates/mtr-test-runner-api" }
mtr-cache = { path = "crates/mtr-cache" }
mtr-config = { path = "crates/mtr-config" }

serde = { version = "1", features = ["derive"] }
serde_json = "1"
wait-timeout = "0.2.1"
