[package]
name = "mtr-cli"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
mtr-types.workspace = true
mtr-mutators.workspace = true
mtr-instrument.workspace = true
mtr-test-runner-api.workspace = true
mtr-runner-jest.workspace = true
mtr-runner-vitest.workspace = true
mtr-cache.workspace = true
mtr-config.workspace = true
serde.workspace = true
serde_json.workspace = true
schemars = "1.2.2"
oxc_span = "0.144.0"
glob = "0.3"
clap = { version = "4", features = ["derive"] }
